### ISSUE TITLE
Wasm memory preparation error

### ISSUE THREAD

**Issue by kino-ma** [kino-ma/Wasmore#34]
Sometimes Node fails to prepare a Wasm memory with the following error.
This occurs when the number of invokers reached around 45-60, but not always.

```
failed to asynchronously prepare wasm: RangeError: WebAssembly.instantiate(): Out of memory: wasm memory
[RangeError: WebAssembly.instantiate(): Out of memory: wasm memory]
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

Error [RangeError]: WebAssembly.Instance(): Out of memory: wasm memory
    at Object.<anonymous> (/home/kino-ma/serverless-edge/node_modules/faas-app/faas_lib.js:145:22)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/kino-ma/serverless-edge/server/invoker/workers/wasm.js:4:14)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)

Node.js v17.1.0
```

**Comment by kino-ma** [comment]
This problem is related to the size of virtual memory that Node.js can use ([nodejs issue](https://github.com/nodejs/node/issues/40201)).
I can avoid the error by running `ulimit -v unlimited` before starting the server.

**Comment by kino-ma** [comment]
> I can avoid the error by running `ulimit -v unlimited` before starting the server.

This did not solve the issue actually
